### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Set up the race track (background)
- [x] Position your car so that users can see it
- [x] Resize car
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
