### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add event listener for 'keydown' events on the document
- [x] rotate car with event listener
- [x] check functionality and for any bugs
- [x] remove unnecessary code/styling
