### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location to your data model to hold car's x and y coordinates on the page.
- [x] Check if data model takes x and y coordinates.
- [x] Use absolute positioning for image
- [x] Listen to space bar to start car
- [x] Start the car with space bar
- [x] Use the style property of element objects to change your car's top and left box offset styles
- [x] Move car every 16 milliseconds for a smooth movement
- [x] check for functionality and bugs
- [x] remove unnecessary code/styling
