### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add bolean to data model to indicate whether or not car started
- [x] Check if boolean updates every time hits Space
- [x] Make car function work according to boolean value
