### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Change function to recognize direction
- [x] Move car based on direction 
- [x] Move car only when car is on
